<?php

namespace Database\Seeders;

use App\Models\NaceHazardClass;
use Illuminate\Database\Seeder;

/**
 * Resmi "İş Sağlığı ve Güvenliğine İlişkin İşyeri Tehlike Sınıfları Tebliği" NACE kodu /
 * tehlike sınıfı referans verisi. KISMİ VERİ — internet üzerinden ulaşılabilen kaynaklardan
 * çıkarılan, doğrulanmış ama TAMAMLANMAMIŞ bir alt küme: sadece NACE A (Tarım/Ormancılık/
 * Balıkçılık, 01-03), B (Madencilik, 05-09) ve C bölümünün büyük kısmı (İmalat, 10-20.59)
 * kapsanıyor. Kalan bölümler (21-99: eczacılık/kauçuk/metal/makine imalatından başlayıp
 * inşaat, ticaret, ulaştırma, konaklama, bilgi/iletişim, finans, gayrimenkul, mesleki/idari
 * hizmetler, kamu, eğitim, sağlık, sanat/eğlence ve diğer hizmetlere kadar) HENÜZ EKLENMEDİ.
 * Kullanıcı resmi tebliğin tam PDF/Excel halini paylaşırsa tam liste buraya eklenebilir.
 * İdempotent: updateOrCreate ile nace_code üzerinden çalışır, tekrar çalıştırmak güvenlidir.
 */
class NaceHazardClassSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [

    ['nace_code' => '01.11.07', 'activity_name' => 'Baklagillerin yetiştirilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.11.12', 'activity_name' => 'Tahıl yetiştiriciliği', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.11.14', 'activity_name' => 'Yağlı tohum yetiştiriciliği', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.12.14', 'activity_name' => 'Çeltik yetiştirilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.13.17', 'activity_name' => 'Şeker pancarı yetiştirilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.13.18', 'activity_name' => 'Yenilebilir kök ve yumru yetiştiriciliği', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.13.19', 'activity_name' => 'Diğer sebze tohumlarının yetiştiriciliği', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.13.20', 'activity_name' => 'Meyvesi yenen sebzelerin yetiştirilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.13.21', 'activity_name' => 'Mantar ve yer mantarları yetiştirilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.13.22', 'activity_name' => 'Köklü sebzelerin yetiştirilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.13.23', 'activity_name' => 'Yapraklı sebzelerin yetiştirilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.14.01', 'activity_name' => 'Şeker kamışı yetiştirilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.15.01', 'activity_name' => 'Tütün yetiştiriciliği', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.16.02', 'activity_name' => 'Pamuk yetiştiriciliği', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.16.90', 'activity_name' => 'Diğer lifli bitkilerin yetiştirilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.19.01', 'activity_name' => 'Hayvan yemi bitkilerinin yetiştiriciliği', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.19.02', 'activity_name' => 'Çiçek yetiştiriciliği', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.19.90', 'activity_name' => 'Tek yıllık diğer bitkisel ürünlerin yetiştirilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.21.05', 'activity_name' => 'Üzüm yetiştiriciliği', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.22.05', 'activity_name' => 'Tropikal ve subtropikal meyvelerin yetiştiriciliği', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.23.02', 'activity_name' => 'Turunçgillerin yetiştirilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.24.04', 'activity_name' => 'Yumuşak/sert çekirdekli meyvelerin yetiştirilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.25.08', 'activity_name' => 'Diğer ağaç/çalı meyvelerinin yetiştirilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.25.09', 'activity_name' => 'Fındık yetiştiriciliği', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.26.02', 'activity_name' => 'Zeytin yetiştiriciliği', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.26.90', 'activity_name' => 'Diğer yağlı meyvelerin yetiştiriciliği', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.27.02', 'activity_name' => 'Çay yetiştiriciliği', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.27.90', 'activity_name' => 'İçecek üretiminde kullanılan diğer bitkisel ürünlerin yetiştiriciliği', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.28.01', 'activity_name' => 'Baharatlık/aromatik bitkisel ürünlerin yetiştirilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.29.01', 'activity_name' => 'Diğer çok yıllık bitkisel ürünlerin yetiştirilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.30.03', 'activity_name' => 'Dikim için sebze/meyve fidesi yetiştirilmesi', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '01.30.04', 'activity_name' => 'Dikim için çiçek ve bitkilerin yetiştirilmesi', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '01.41.31', 'activity_name' => 'Sütü sağılan büyük baş hayvan yetiştiriciliği', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.42.09', 'activity_name' => 'Diğer sığır ve manda yetiştiriciliği', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.43.01', 'activity_name' => 'At ve at benzeri hayvan yetiştiriciliği', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.44.01', 'activity_name' => 'Deve yetiştiriciliği', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.45.01', 'activity_name' => 'Koyun ve keçi yetiştiriciliği', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.46.01', 'activity_name' => 'Domuz yetiştiriciliği', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.47.01', 'activity_name' => 'Kümes hayvanlarının yetiştirilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.47.02', 'activity_name' => 'Kuluçkahanelerin faaliyetleri', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.47.03', 'activity_name' => 'Kümes hayvanlarından yumurta üretilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.49.01', 'activity_name' => 'Arıcılık, bal ve bal mumu üretilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.49.02', 'activity_name' => 'İpekböceği yetiştiriciliği ve koza üretimi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.49.03', 'activity_name' => 'Evcil hayvanların yetiştirilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.49.05', 'activity_name' => 'Deve kuşlarının yetiştirilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.49.90', 'activity_name' => 'Yarı evcilleştirilmiş hayvanların yetiştirilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.50.06', 'activity_name' => 'Karma çiftçilik', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.61.01', 'activity_name' => 'Bitkisel üretimi destekleyici gübreleme vb. faaliyetler', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.61.02', 'activity_name' => 'Bitkisel üretimi destekleyici hasat ve harmanlama faaliyetleri', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.61.03', 'activity_name' => 'Bitkisel üretimi destekleyici sulama faaliyetleri', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.61.04', 'activity_name' => 'Bitkisel üretimi destekleyici ilaçlama ve zirai mücadele', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '01.61.05', 'activity_name' => 'Çiçek yetiştiriciliğini destekleyici faaliyetler', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.61.06', 'activity_name' => 'Hava yoluyla yapılan bitkisel üretim destekleyici faaliyetler', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '01.62.01', 'activity_name' => 'Hayvan üretimini destekleyici faaliyetler', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.62.02', 'activity_name' => 'Hayvan üretimini destekleyici sürü testi vb. faaliyetler', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.63.01', 'activity_name' => 'Hasat sonrası ürünlerin ayıklanması ve temizlenmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.63.02', 'activity_name' => 'Sert kabuklu ürünlerin kabuklarının kırılması', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.63.03', 'activity_name' => 'Haşhaş vb. ürünlerin sürtme ve temizlenmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.63.04', 'activity_name' => 'Mısır vb. ürünlerin tanelenmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.63.05', 'activity_name' => 'Tütünün sınıflandırılması vb. hizmetler', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '01.63.06', 'activity_name' => 'Nişastalı kök ürünlerinin ayıklanması', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.63.07', 'activity_name' => 'Çırçırlama faaliyeti', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.63.90', 'activity_name' => 'Hasat sonrası bitkisel ürünler ile ilgili diğer faaliyetler', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.64.01', 'activity_name' => 'Üretim amaçlı tohum işleme hizmetleri', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.70.01', 'activity_name' => 'Ticari olmayan av hayvanı avlama ve yakalama', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '01.70.02', 'activity_name' => 'Ticari olan av hayvanı avlama ve yakalama', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '02.10.01', 'activity_name' => 'Baltalık ormanların yetiştirilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '02.10.02', 'activity_name' => 'Orman yetiştirmek için fidan ve tohum üretimi', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '02.10.03', 'activity_name' => 'Orman ağaçlarının yetiştirilmesi', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '02.20.01', 'activity_name' => 'Endüstriyel ve yakacak odun üretimi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '02.30.01', 'activity_name' => 'Tabii yetişen odun dışı orman ürünlerinin toplanması', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '02.40.01', 'activity_name' => 'Ormanda ağaçların kesilmesi vb. destekleyici faaliyetler', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '02.40.02', 'activity_name' => 'Ormanda kesilmiş ağaçların taşınması vb. faaliyetleri', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '02.40.03', 'activity_name' => 'Ormanda silvikültürel hizmet faaliyetleri', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '02.40.04', 'activity_name' => 'Ormanı zararlılara karşı koruma faaliyetleri', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '02.40.05', 'activity_name' => 'Ormanı yangın ve kaçak kesime karşı koruma', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '02.40.06', 'activity_name' => 'Orman yolu yapımı ve bakımı faaliyetleri', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '02.40.07', 'activity_name' => 'Diğer ormancılık hizmet faaliyetleri', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '03.11.01', 'activity_name' => 'Deniz ve kıyı sularında yapılan balıkçılık', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '03.11.02', 'activity_name' => 'Deniz kabuklularının toplanması', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '03.12.01', 'activity_name' => 'Tatlı sularda yapılan balıkçılık', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '03.21.01', 'activity_name' => 'Denizde yapılan balık yetiştiriciliği', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '03.21.02', 'activity_name' => 'Denizde yapılan diğer su ürünleri yetiştiriciliği', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '03.22.01', 'activity_name' => 'Tatlı sularda yapılan balık yetiştiriciliği', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '03.22.02', 'activity_name' => 'Tatlısu ürünleri yetiştiriciliği', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '05.10.01', 'activity_name' => 'Taş kömürü madenciliği', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '05.20.01', 'activity_name' => 'Linyit madenciliği', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '06.10.01', 'activity_name' => 'Ham petrolün çıkarılması', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '06.20.01', 'activity_name' => 'Doğalgaz çıkarılması', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '07.10.01', 'activity_name' => 'Demir cevheri madenciliği', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '07.21.01', 'activity_name' => 'Uranyum metalinin ayrıştırılması', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '07.21.02', 'activity_name' => 'Toryum metalinin ayrıştırılması', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '07.21.03', 'activity_name' => 'Uranyum madenciliği', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '07.21.04', 'activity_name' => 'Toryum madenciliği', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '07.21.05', 'activity_name' => 'Sarı pasta imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '07.29.01', 'activity_name' => 'Değerli metal madenciliği', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '07.29.02', 'activity_name' => 'Alüminyum madenciliği', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '07.29.03', 'activity_name' => 'Bakır madenciliği', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '07.29.04', 'activity_name' => 'Nikel madenciliği', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '07.29.05', 'activity_name' => 'Kurşun, çinko ve kalay madenciliği', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '07.29.06', 'activity_name' => 'Krom madenciliği', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '07.29.07', 'activity_name' => 'Demir dışı diğer metal cevherleri madenciliği', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '08.11.01', 'activity_name' => 'Mermer ocakçılığı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '08.11.02', 'activity_name' => 'Granit ocakçılığı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '08.11.03', 'activity_name' => 'Yapı taşları ocakçılığı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '08.11.04', 'activity_name' => 'Süsleme ve yapı taşlarının kırılması ve kesilmesi', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '08.11.05', 'activity_name' => 'Dolomit ve kayağan taşı ocakçılığı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '08.11.06', 'activity_name' => 'Kireçtaşı ocakçılığı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '08.11.07', 'activity_name' => 'Tebeşir, alçıtaşı ve anhidrit ocakçılığı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '08.12.01', 'activity_name' => 'Çakıl ve kum ocakçılığı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '08.12.02', 'activity_name' => 'Çakıl taşlarının kırılması ve parçalanması', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '08.12.03', 'activity_name' => 'Kil, refrakter kil ve kaolin madenciliği', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '08.91.01', 'activity_name' => 'Kimyasal ve gübreleme amaçlı mineral madenciliği', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '08.91.02', 'activity_name' => 'Bor mineralleri madenciliği', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '08.91.03', 'activity_name' => 'Kükürt madenciliği', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '08.91.04', 'activity_name' => 'Guano madenciliği', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '08.91.05', 'activity_name' => 'Kehribar, Oltu taşı ve lületaşı ocakçılığı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '08.92.01', 'activity_name' => 'Turba çıkarılması ve toplanması', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '08.93.01', 'activity_name' => 'Kaya tuzunun çıkarımı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '08.93.02', 'activity_name' => 'Deniz, göl ve kaynak tuzu üretimi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '08.99.01', 'activity_name' => 'Aşındırıcı materyaller ve feldispat madenciliği', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '08.99.02', 'activity_name' => 'Doğal asfalt ve bitüm madenciliği', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '08.99.03', 'activity_name' => 'Kıymetli ve yarı kıymetli taşların ocakçılığı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '08.99.04', 'activity_name' => 'Grafit ocakçılığı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '08.99.05', 'activity_name' => 'Elmas madenciliği', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '08.99.90', 'activity_name' => 'Başka yerde sınıflandırılmamış madencilik ve taşocakçılığı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '09.10.01', 'activity_name' => 'Doğalgaz sıvılaştırılması ve gaz haline getirilmesi', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '09.10.02', 'activity_name' => 'Petrol ve gaz çıkarımıyla ilgili sondaj hizmetleri', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '09.10.03', 'activity_name' => 'Petrol ve gaz çıkarımı ile ilgili vinç ve sondaj kulesi hizmetleri', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '09.90.01', 'activity_name' => 'Madencilik ve taş ocakçılığını destekleyici diğer hizmetler', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '09.90.02', 'activity_name' => 'Test amaçlı sondaj faaliyetleri', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '10.11.01', 'activity_name' => 'Sığır, koyun, keçi vb. kesimi ve et işlenmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.12.01', 'activity_name' => 'Kümes hayvanları etlerinin üretimi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.12.02', 'activity_name' => 'Kümes hayvanlarının kesilmesi, temizlenmesi veya paketlenmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.12.03', 'activity_name' => 'Kümes hayvanlarının yağlarının sofra yağına çevrilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.12.04', 'activity_name' => 'Kuş tüyü ve ince kuş tüyü imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.13.01', 'activity_name' => 'Et ve kümes hayvanları etlerinden pişmemiş köfte imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.13.02', 'activity_name' => 'Et ürünlerinden sosis, salam, sucuk vb. imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.13.03', 'activity_name' => 'Et ve sakatat unları imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.13.04', 'activity_name' => 'Sakatat ve yağlarından yenilebilir ürünlerin imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.20.03', 'activity_name' => 'Balık, kabuklu deniz hayvanlarının işlenmesi ve saklanması', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.20.04', 'activity_name' => 'Balık, kabuklu deniz hayvanı ve yumuşakça ürünlerinin üretimi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.20.05', 'activity_name' => 'Balık unları ve peletlerinin üretilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.20.06', 'activity_name' => 'Balık işlenmesi ve saklanması yapan tekne ve gemilerin faaliyetleri', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.20.07', 'activity_name' => 'Pişirilmemiş balık yemekleri imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.20.08', 'activity_name' => 'Su omurgasızlarının unları ve yenilemeyen ürünlerinin üretimi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.31.01', 'activity_name' => 'Patatesin işlenmesi ve saklanması', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.31.02', 'activity_name' => 'Patates cipsi ve patates unu imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.32.01', 'activity_name' => 'Katkısız sebze ve meyve suları imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.32.02', 'activity_name' => 'Konsantre meyve ve sebze suyu imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.39.01', 'activity_name' => 'Sebze ve meyve konservesi imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.39.02', 'activity_name' => 'Kavrulmuş, tuzlanmış sert kabuklu yemişler imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.39.03', 'activity_name' => 'Meyve ve sebzelerden jöle, pekmez, marmelat, reçel imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.39.04', 'activity_name' => 'Tuzlu su, sirke, sirkeli su ile korunarak saklanan sebze ve meyveler', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.39.05', 'activity_name' => 'Dondurulmuş veya kurutulmuş meyve ve sebzelerin imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.39.06', 'activity_name' => 'Leblebi imalatı ve kavrulmuş çekirdek üretimi', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.39.07', 'activity_name' => 'Susamın işlenmesi ve tahin imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.39.90', 'activity_name' => 'Meyve ve sebzelerin başka yöntemlerle işlenmesi ve saklanması', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.41.01', 'activity_name' => 'Ayçiçek yağı imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.41.02', 'activity_name' => 'Bitkisel sıvı yağ imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.41.03', 'activity_name' => 'Beziryağı imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.41.05', 'activity_name' => 'Prina yağı imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.41.06', 'activity_name' => 'Kakao yağı ve diğer benzer yağların imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.41.07', 'activity_name' => 'Zeytinyağı imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.41.10', 'activity_name' => 'Balık ve deniz memelilerinden yağ elde edilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.41.11', 'activity_name' => 'Hayvansal katı ve sıvı yağların imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.42.01', 'activity_name' => 'Margarin ve benzeri yenilebilir katı yağların imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.51.01', 'activity_name' => 'Süt imalatı ve işlenmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.51.02', 'activity_name' => 'Peynir, lor ve çökelek imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.51.03', 'activity_name' => 'Süt tozu ve peynir özü imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.51.04', 'activity_name' => 'Süt temelli hafif içeceklerin imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.51.05', 'activity_name' => 'Sütten yapılan diğer ürünlerin imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.52.01', 'activity_name' => 'Dondurma imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.52.02', 'activity_name' => 'Şerbetli diğer yenilebilen buzlu gıdaların imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.61.01', 'activity_name' => 'Kahvaltılık tahıl ürünleri imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.61.02', 'activity_name' => 'Tahılların öğütülmesi ve un imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.61.05', 'activity_name' => 'Pirinç, pirinç ezmesi ve pirinç unu imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.61.06', 'activity_name' => 'İrmik imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.61.07', 'activity_name' => 'Ön pişirme yapılmış tane halde hububat imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.61.08', 'activity_name' => 'Sebzelerin ve baklagillerin öğütülmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.61.09', 'activity_name' => 'Fırıncılık ürünlerinin imalatında kullanılan hamur karışımları', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.61.10', 'activity_name' => 'Dövülmüş diğer tahıl ürünlerinin imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.62.01', 'activity_name' => 'Nişasta imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.62.02', 'activity_name' => 'Glikoz, glikoz şurubu ve benzeri ürünlerin imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.62.04', 'activity_name' => 'Yaş mısırın öğütülmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.62.05', 'activity_name' => 'Glüten imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.62.06', 'activity_name' => 'Mısır yağı imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.71.01', 'activity_name' => 'Taze pastane ürünleri imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.71.02', 'activity_name' => 'Fırın ürünleri imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.71.03', 'activity_name' => 'Hamur tatlıları imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.72.01', 'activity_name' => 'Peksimet ve bisküvi imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.72.02', 'activity_name' => 'Dayanıklı fırın ve pastane ürünlerinin imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.72.03', 'activity_name' => 'Tatlandırılmamış dayanıklı hamur tatlıları imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.73.03', 'activity_name' => 'Makarna, şehriye, kuskus imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.81.01', 'activity_name' => 'Şeker imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.81.03', 'activity_name' => 'Akçaağaç şurubu imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.82.01', 'activity_name' => 'Çikolata ve kakao içeren şekerlemelerin imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.82.02', 'activity_name' => 'Şekerlemelerin ve şeker pastillerinin imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.82.03', 'activity_name' => 'Sürülerek yenebilen kakaolu ürünler imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.82.04', 'activity_name' => 'Lokum, pişmaniye, helva, karamel vb. imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.82.05', 'activity_name' => 'Ciklet imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.82.06', 'activity_name' => 'Sert kabuklu meyve şekerleme imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.82.07', 'activity_name' => 'Kakao tozu, kakao ezmesi ve kakao yağı imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.83.01', 'activity_name' => 'Çay ürünleri imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.83.02', 'activity_name' => 'Kahve ürünleri imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.83.03', 'activity_name' => 'Bitkisel çayların imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.83.04', 'activity_name' => 'Kahve içeren ürünlerin imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.84.01', 'activity_name' => 'Baharat imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.84.02', 'activity_name' => 'Sirke ve sirke ikamelerinin imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.84.03', 'activity_name' => 'Sos ve çeşnilerin imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.84.05', 'activity_name' => 'Gıda tuzu imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.85.01', 'activity_name' => 'Hazır yemek imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.86.01', 'activity_name' => 'Bebek ve çocukların beslenmesinde kullanılan müstahzarlar', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.86.02', 'activity_name' => 'Hastalar ve diyet amaçlı homojenize gıda müstahzarları', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.86.03', 'activity_name' => 'Besin yönünden zenginleştirilmiş sporcu yiyecekleri imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.89.01', 'activity_name' => 'Hazır çorba ve et suyu konsantreleri imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.89.02', 'activity_name' => 'Maya ve kabartma tozu imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.89.04', 'activity_name' => 'Suni bal, yumurta albümini vb. imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.89.05', 'activity_name' => 'Bitki özsu ve ekstreleri ile peptik maddeler imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.89.06', 'activity_name' => 'Çeşitli gıda ürünleri imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '10.91.01', 'activity_name' => 'Çiftlik hayvanları için hazır yem imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '10.92.01', 'activity_name' => 'Ev hayvanları için hazır gıda imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '11.01.01', 'activity_name' => 'Damıtılmış alkollü içeceklerin imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '11.01.02', 'activity_name' => 'Damıtılmış alkollü içeceklerle karıştırılmış içki imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '11.01.03', 'activity_name' => 'Etil alkol üretimi', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '11.02.01', 'activity_name' => 'Üzümden şarap, köpüklü şarap imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '11.02.02', 'activity_name' => 'Üzüm şırası imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '11.03.01', 'activity_name' => 'Elma şarabı ve diğer meyve şaraplarının imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '11.04.02', 'activity_name' => 'Diğer damıtılmamış mayalı içeceklerin imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '11.05.01', 'activity_name' => 'Bira imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '11.06.01', 'activity_name' => 'Malt imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '11.07.01', 'activity_name' => 'Doğal veya suni maden sularının üretimi', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '11.07.02', 'activity_name' => 'Diğer alkolsüz içeceklerin üretimi', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '11.07.03', 'activity_name' => 'İçme suyu üretimi', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '11.07.04', 'activity_name' => 'Boza imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '12.00.04', 'activity_name' => 'Tütün ürünleri imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.10.03', 'activity_name' => 'Doğal pamuk elyafının imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.10.05', 'activity_name' => 'Doğal yün ve tiftik elyafının imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.10.06', 'activity_name' => 'Doğal jüt, keten ve diğer bitkisel tekstil elyaflarının imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.10.08', 'activity_name' => 'İpeğin kozadan ayrılması ve sarılması', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.10.09', 'activity_name' => 'Sentetik veya suni devamsız elyafın kardelenmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.10.10', 'activity_name' => 'Doğal ipeğin bükülmesi ve iplik haline getirilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.10.12', 'activity_name' => 'Pamuk elyafının bükülmesi ve iplik haline getirilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.10.13', 'activity_name' => 'Yün ve tiftik elyafının bükülmesi ve iplik haline getirilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.10.14', 'activity_name' => 'Jüt, keten ve diğer bitkisel tekstil elyaflarının bükülmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.10.15', 'activity_name' => 'Suni ve sentetik elyafların bükülmesi ve iplik haline getirilmesi', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.20.14', 'activity_name' => 'Kot kumaşı imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.20.16', 'activity_name' => 'Pamuklu dokuma kumaş imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.20.17', 'activity_name' => 'Doğal kıl ve yünden dokuma kumaş imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.20.19', 'activity_name' => 'Doğal ipekten kumaş imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.20.20', 'activity_name' => 'Keten, rami, kenevir, jüt elyaflarından dokuma kumaş', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.20.21', 'activity_name' => 'Havlı, şönil, havlu, pelüş kumaşlar imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.20.22', 'activity_name' => 'Suni ve sentetik filamentlerden dokuma kumaş imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.20.23', 'activity_name' => 'Dokuma yoluyla imitasyon kürk kumaş imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.20.24', 'activity_name' => 'Cam elyafından dokuma kumaş imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.30.01', 'activity_name' => 'Kumaş ve tekstil ürünlerini ağartma ve boyama', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.30.02', 'activity_name' => 'Tekstil elyaf ve ipliklerini ağartma ve boyama', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.30.03', 'activity_name' => 'Kumaş ve tekstil ürünlerine baskı yapılması', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.30.04', 'activity_name' => 'Kumaş ve tekstil ürünlerine diğer bitirme hizmetleri', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.91.01', 'activity_name' => 'Örgü ve tığ işi kumaşların imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.91.02', 'activity_name' => 'Örme yoluyla imitasyon kürk kumaşı imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.92.01', 'activity_name' => 'Yatak örtü takımları ve tuvalet örtülerin imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.92.02', 'activity_name' => 'Yorgan, minder, puf, yastık imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.92.03', 'activity_name' => 'Perdelerin ve iç storların imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.92.04', 'activity_name' => 'Tekstilden temizlik bezleri imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.92.05', 'activity_name' => 'Battaniye imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.92.06', 'activity_name' => 'Tekstilden çuval, torba, çanta imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.92.07', 'activity_name' => 'Can yeleği ve can kurtaran simidi imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.92.08', 'activity_name' => 'Paraşüt ve rotoşüt imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.92.09', 'activity_name' => 'Bayrak, sancak ve flama imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.92.10', 'activity_name' => 'Tekstilden örtü ve kılıf imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.92.11', 'activity_name' => 'Branda, tente, yelken, çadır imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.93.01', 'activity_name' => 'Halı ve kilim imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.93.02', 'activity_name' => 'Halı ve kilim için çözgücülük faaliyetleri', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '13.94.02', 'activity_name' => 'Ağ ve ağ ürünleri imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '13.94.03', 'activity_name' => 'Sicim, urgan, halat, kordon imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.95.01', 'activity_name' => 'Dokusuz kumaşlar ve bunlardan yapılan ürünlerin imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.96.01', 'activity_name' => 'Metalize iplik ve gipe iplik imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.96.02', 'activity_name' => 'Tekstil parça halinde kordonlar imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '13.96.03', 'activity_name' => 'Dar dokuma kumaşların imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.96.04', 'activity_name' => 'Tekstil dokuma etiket, rozet, arma imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '13.96.05', 'activity_name' => 'Teknik kullanım amaçlı tekstil ürünleri imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.96.06', 'activity_name' => 'Kord bezi imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.96.07', 'activity_name' => 'Tekstille kaplanmış kauçuk iplik imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.96.08', 'activity_name' => 'Kaplanmış veya emdirilmiş tekstil kumaşlarının imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.99.02', 'activity_name' => 'Oya, dantel ve nakış imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.99.03', 'activity_name' => 'Keçe ve basınçlı hassas giysi dokumaları imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.99.04', 'activity_name' => 'Tekstil kırpıntısı imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '13.99.06', 'activity_name' => 'Gipe iplik ve şeritlerin imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '14.11.05', 'activity_name' => 'Deri giyim eşyası imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '14.12.07', 'activity_name' => 'Endüstriyel iş giysisi imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '14.12.08', 'activity_name' => 'Mesleki kıyafet imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '14.13.04', 'activity_name' => 'Dış giyim eşyası imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '14.13.05', 'activity_name' => 'Siparişe göre dış giyim eşyası imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '14.13.06', 'activity_name' => 'Sahne ve gösteri elbiseleri imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '14.13.07', 'activity_name' => 'Gelinlik imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '14.14.01', 'activity_name' => 'Gömlek, tişört, bluz imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '14.14.02', 'activity_name' => 'Gecelik, pijama, bornoz imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '14.14.03', 'activity_name' => 'İç çamaşırı imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '14.14.04', 'activity_name' => 'Çorap bağları, jartiyer vb. iç giyim aksesuarları imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '14.19.01', 'activity_name' => 'Spor ve antrenman giysileri imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '14.19.02', 'activity_name' => 'Yazma, tülbent, eşarp imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '14.19.04', 'activity_name' => 'Eldiven, kemer, şal, papyon vb. giysi aksesuarları imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '14.19.05', 'activity_name' => 'Bebek giyim eşyası ve aksesuarları imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '14.19.07', 'activity_name' => 'Şapka, kep, başlık imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '14.19.08', 'activity_name' => 'Giyim eşyası imalatı (keçeden veya dokusuz kumaştan)', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '14.20.04', 'activity_name' => 'Post, kürk ürünleri ve parçaların imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '14.20.05', 'activity_name' => 'Post, kürk giyim eşyası ve aksesuarları imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '14.31.01', 'activity_name' => 'Çorap imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '14.39.01', 'activity_name' => 'Örgü ve tığ işi diğer giyim eşyası imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '15.11.10', 'activity_name' => 'Deri ve kürklü deri imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '15.11.11', 'activity_name' => 'Kürklü derinin ve postların işlenmesi', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '15.11.13', 'activity_name' => 'Deri ve kösele esaslı terkip imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '15.11.14', 'activity_name' => 'İşlenmiş derinin ütülenmesi ve kurutulması', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '15.12.07', 'activity_name' => 'Deri el çantası, cüzdan ve benzeri ürünlerin imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '15.12.08', 'activity_name' => 'Saraçlık ve koşum takımı imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '15.12.09', 'activity_name' => 'Deri saat kayışı imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '15.12.10', 'activity_name' => 'Plastik veya kauçuk saat kayışı imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '15.12.11', 'activity_name' => 'Kumaş ve diğer malzemelerden saat kayışı imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '15.12.12', 'activity_name' => 'Taşıma ve konveyör bantları imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '15.20.15', 'activity_name' => 'Deriden ayakkabı, bot, terlik imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '15.20.17', 'activity_name' => 'Plastik veya kauçuktan ayakkabı imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '15.20.18', 'activity_name' => 'Tekstilden ve diğer malzemelerden ayakkabı imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '15.20.19', 'activity_name' => 'Ayakkabı parçalarının imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '16.10.01', 'activity_name' => 'Kereste imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '16.10.02', 'activity_name' => 'Ahşap demir yolu traversi imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '16.10.03', 'activity_name' => 'Ağaç yünü, ağaç unu ve ahşap ürünleri imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '16.10.05', 'activity_name' => 'Ahşap döşemelerin imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '16.10.06', 'activity_name' => 'Tomruk ve kerestelerin kurutulması ve emprenyelenmesi', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '16.21.01', 'activity_name' => 'Kaplamalık plaka ve levha imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '16.21.02', 'activity_name' => 'Kontrplak, mdf ve levha imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '16.22.01', 'activity_name' => 'Birleştirilebilir ahşap parke imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '16.23.01', 'activity_name' => 'Ahşap pencere, kapı ve merdiven imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '16.23.02', 'activity_name' => 'Ahşap prefabrik yapılar imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '16.23.90', 'activity_name' => 'İnşaat doğrama ve marangozluk ürünleri imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '16.24.01', 'activity_name' => 'Kutu, sandık, fıçı vb. ahşap ambalaj imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '16.24.02', 'activity_name' => 'Palet ve diğer ahşap yükleme tablaları imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '16.24.03', 'activity_name' => 'Ahşap kablo makarası imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '16.29.01', 'activity_name' => 'Ahşap mutfak ve sofra eşyası imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '16.29.02', 'activity_name' => 'Mantar ürünleri imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '16.29.03', 'activity_name' => 'Sedef kakma ahşap işleri imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '16.29.04', 'activity_name' => 'Ahşaptan iş aletleri ve sapları imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '16.29.05', 'activity_name' => 'Ahşap çerçeve ve eşyaların imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '16.29.07', 'activity_name' => 'Hasır eşyaların imalatı', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '16.29.90', 'activity_name' => 'Diğer ağaç ürünleri imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '17.11.08', 'activity_name' => 'Kağıt hamuru imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '17.12.07', 'activity_name' => 'Kağıt ve mukavva imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '17.21.10', 'activity_name' => 'Kağıt evrak tasnif kutuları imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '17.21.11', 'activity_name' => 'Kağıt ve kartondan torba ve çanta imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '17.21.12', 'activity_name' => 'Kağıt veya mukavvadan koli, kutu imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '17.21.13', 'activity_name' => 'Oluklu kağıt ve mukavva imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '17.22.02', 'activity_name' => 'Tuvalet kağıdı ve kağıt mendil imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '17.22.03', 'activity_name' => 'Kağıt veya mukavvadan tepsi, tabak, kase imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '17.22.04', 'activity_name' => 'Hijyenik havlu ve tamponlar imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '17.23.04', 'activity_name' => 'Karbon kağıdı ve kendinden kopyalı kağıt imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '17.23.06', 'activity_name' => 'Kağıt kırtasiye malzemeleri imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '17.23.07', 'activity_name' => 'Dosya ve klasör imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '17.23.08', 'activity_name' => 'Basım ve yazım kağıdı imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '17.23.09', 'activity_name' => 'Zarf ve mektup kartı imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '17.24.02', 'activity_name' => 'Duvar kağıdı imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '17.24.03', 'activity_name' => 'Tekstil duvar kaplamalarının imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '17.29.01', 'activity_name' => 'Kağıt veya mukavvadan etiket imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '17.29.02', 'activity_name' => 'Filtre kağıdı ve karton imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '17.29.03', 'activity_name' => 'Sigara kağıdı ve bobin imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '17.29.04', 'activity_name' => 'Jakar makineleri kartları imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '18.11.01', 'activity_name' => 'Gazetelerin, dergilerin basım hizmetleri', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '18.12.01', 'activity_name' => 'Çıkartma, takvim, katalog, poster vb. basım', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '18.12.02', 'activity_name' => 'Dergilerin az sıklıkta basım hizmetleri', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '18.12.03', 'activity_name' => 'Kitap, kitapçık, müzik eserlerinin basım', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '18.12.04', 'activity_name' => 'Röprodüksiyon basımı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '18.12.05', 'activity_name' => 'Serigrafi faaliyetleri', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '18.12.06', 'activity_name' => 'Posta pulu, damga, değerli kağıtların basımı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '18.12.07', 'activity_name' => 'Plastik, cam, metal, ağaç, seramik üstüne baskı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '18.13.01', 'activity_name' => 'Baskı klişeleri ve basım unsurlarının üretilmesi', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '18.13.02', 'activity_name' => 'Basım öncesi bilgisayar destekli hizmetler', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '18.14.01', 'activity_name' => 'Ciltçilik ve ilgili hizmetler', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '18.20.02', 'activity_name' => 'Ses ve görüntü kayıtlarının çoğaltılması', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '18.20.03', 'activity_name' => 'Yazılımların çoğaltılması hizmetleri', 'hazard_class' => 'az_tehlikeli'],
    ['nace_code' => '19.10.10', 'activity_name' => 'Linyit ve turbadan kok fırını ürünleri imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '19.10.11', 'activity_name' => 'Taşkömüründen kok fırını ürünleri imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '19.20.12', 'activity_name' => 'Turba, linyit ve taş kömürü briketleri imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '19.20.15', 'activity_name' => 'Petrol türevi yakıtların imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '19.20.16', 'activity_name' => 'Petrolden madeni yağların imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '19.20.17', 'activity_name' => 'Vazelin, parafin mumu, petrol bitümeni imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '19.20.19', 'activity_name' => 'Petrol yağı ürünlerinin imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.11.01', 'activity_name' => 'Sanayi gazları imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.12.01', 'activity_name' => 'Boya maddeleri ve pigment imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.12.02', 'activity_name' => 'Tabaklama ekstreleri ve renklendirme maddelerinin imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.13.02', 'activity_name' => 'Metalik halojenler ve klor bileşikleri imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.13.03', 'activity_name' => 'Sülfidler, sülfatlar, fosfatlar ve nitratların imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.13.04', 'activity_name' => 'Karbonatların imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.13.06', 'activity_name' => 'Uranyum ve toryum cevherlerinin zenginleştirilmesi', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.13.07', 'activity_name' => 'Metal tuzları ve temel inorganik kimyasalların imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.13.90', 'activity_name' => 'Kimyasal elementler ve inorganik bileşiklerin imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.14.01', 'activity_name' => 'Temel organik kimyasalların imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.14.04', 'activity_name' => 'Odunun ve kömür katranının damıtılması', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.14.05', 'activity_name' => 'Tabii reçine ve türevleri imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '20.15.01', 'activity_name' => 'Kimyasal gübre imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.15.02', 'activity_name' => 'Bileşik azotlu ürünlerin imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.16.01', 'activity_name' => 'Birincil formda poliamitler ve reçineler imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.16.02', 'activity_name' => 'Birincil formda alkid ve polyester reçineler imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.16.03', 'activity_name' => 'Birincil formda polimerlerin imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.16.04', 'activity_name' => 'Birincil formda silikon ve polimer esaslı iyonlar', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.16.05', 'activity_name' => 'Birincil formda fenolik reçineler ve poliüretanlar', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.17.01', 'activity_name' => 'Birincil formda sentetik kauçuk imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.20.11', 'activity_name' => 'Böcek ilacı ve zararlı ilacı imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.20.12', 'activity_name' => 'Dezenfektan imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.20.13', 'activity_name' => 'Çimlenmeyi önleyici ve bitki gelişim düzenleyici imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.20.14', 'activity_name' => 'Diğer zirai kimyasal ürünlerin imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.30.11', 'activity_name' => 'Boya ve verniklerin imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.30.12', 'activity_name' => 'Macun imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.30.13', 'activity_name' => 'Diğer boya, vernik ve ilgili ürünlerin imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.30.14', 'activity_name' => 'Polyester ve akrilik boya ve verniklerin imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.30.15', 'activity_name' => 'Hazır boya pigmentleri ve emay imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.30.16', 'activity_name' => 'Boya müstahzarları hazır kurutucu imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.30.17', 'activity_name' => 'Elektrostatik toz boya imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.41.01', 'activity_name' => 'Kokulu müstahzarlar ve koku gidericiler imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '20.41.03', 'activity_name' => 'Ham gliserin imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '20.41.04', 'activity_name' => 'Sabun ve deterjan imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '20.41.06', 'activity_name' => 'Cila ve ovalama krem imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '20.42.01', 'activity_name' => 'Ağız ve diş bakım ürünleri imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '20.42.02', 'activity_name' => 'Kolonya imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '20.42.03', 'activity_name' => 'Parfüm ve koku verici ürün imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '20.42.04', 'activity_name' => 'Şampuan ve saç bakım ürünleri imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '20.51.21', 'activity_name' => 'Barut ve itici tozların imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.51.22', 'activity_name' => 'Hazır patlayıcılar ve piroteknik malzeme imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.51.23', 'activity_name' => 'Kibrit imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.52.05', 'activity_name' => 'Tutkal imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.53.02', 'activity_name' => 'Uçucu yağların imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '20.59.01', 'activity_name' => 'Fotografik levha ve filmlerin imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.59.03', 'activity_name' => 'Aktif karbon imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.59.04', 'activity_name' => 'Yağlama müstahzarları imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.59.05', 'activity_name' => 'Yazım ve çizim mürekkepleri imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '20.59.06', 'activity_name' => 'Peptonlar ve protein maddeleri imalatı', 'hazard_class' => 'tehlikeli'],
    ['nace_code' => '20.59.07', 'activity_name' => 'Laboratuvar kültür ortamları imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.59.08', 'activity_name' => 'Elektronik kullanılan macun kıvamında kimyasal imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.59.09', 'activity_name' => 'Bitirme maddeleri ve boya taşıyıcı imalatı', 'hazard_class' => 'cok_tehlikeli'],
    ['nace_code' => '20.59.10', 'activity_name' => 'Dekapaj müstahzarları imalatı', 'hazard_class' => 'cok_tehlikeli'],
        ];

        foreach ($rows as $row) {
            NaceHazardClass::query()->updateOrCreate(
                ['nace_code' => $row['nace_code']],
                ['activity_name' => $row['activity_name'], 'hazard_class' => $row['hazard_class']]
            );
        }
    }
}
